language: cpp
sudo: false

# only run travis on the master branch
branches:
  only:
   - master
   - coverity_scan
   - develop

# define complier for build
compiler:
  - gcc

env:
 global:
  # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
  #   via the "travis encrypt" command using the project repo's public key
  - secure: "Zk3bAxnp4OHPMMZYOSoM2chuMZXomp7BFcT54/Ag6C8RCqtpqQ+E6yHRp861xdWSVo9uZ/uGmD1pwPiIUK8Vs80+OwhFVvtor2MGXyQKX1oFYBg0mo5Z3Xzy+OPa3e0YBbe6SSqdUzDE1hIa7OrU8GWciIMobWQS7XIBbWg3TFU="


# experimental config
#before_install:
#  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#  - sudo apt-get update -qq
#  - sudo apt-get -qq install zlib1g-dev libssl-dev libpcre3-dev libmysqlclient-dev gcc-4.8 g++-4.8
#  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
#  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - zlib1g-dev
      - libssl-dev
      - libpcre3-dev
      - libmysqlclient-dev
      - gcc-4.8
      - g++-4.8
  coverity_scan:
     project:
       name: "AscEmu/AscEmu"
       description: "MMORPG Framework"
   notification_email: autokaori@gmail.com
   build_command_prepend: "make clean"
   build_command:   "make -j 2"
   branch_pattern: coverity_scan

install:
 - mkdir bin
 - cd bin
 - cmake ../

script:
 - cd ..
 - cd bin
 - gcc --version
 - g++ --version
 - cmake --version
 - make -j 2
