sudo: false
language: cpp

os:
  - linux
 # - osx

compiler:
  - gcc
 # - clang

# Do not send any notifications...
#notifications:
#   email: false

#branches:
#  only:
#    - master
#    - coverity_scan

git:
  depth: 1

env:
  global:
    - secure: "Zk3bAxnp4OHPMMZYOSoM2chuMZXomp7BFcT54/Ag6C8RCqtpqQ+E6yHRp861xdWSVo9uZ/uGmD1pwPiIUK8Vs80+OwhFVvtor2MGXyQKX1oFYBg0mo5Z3Xzy+OPa3e0YBbe6SSqdUzDE1hIa7OrU8GWciIMobWQS7XIBbWg3TFU="
# Don't use Clang for Coverity Scan.
#matrix:
#  exlude:
#    - compiler: clang
#      env: TRAVIS_BRANCH=coverity_fix_and_test

before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
    export CC=gcc-4.8 CXX=g++-4.8;
    fi
#  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then
#    brew update;
#    brew install mysql openssl pcre lbzip2;
#    fi

install:
  - mkdir ascemu_build
  - cd ascemu_build
  - cmake ../ -DCMAKE_BUILD_TYPE=Release -DBUILD_TOOLS=1

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - zlib1g-dev
    - libssl-dev
    - libpcre3-dev
    - libbz2-dev
    - libmysqlclient-dev
    - libmysql++-dev
    - gcc-4.8
    - g++-4.8
  coverity_scan:
    project:
      name: "AscEmu/AscEmu"
      description: "3.3.5 World of Warcraft game server"
    notification_email: autokaori@gmail.com
    build_command_prepend: "cmake ../ -DCMAKE_BUILD_TYPE=Release -DBUILD_TOOLS=0 && make clean"
    build_command:   "make -j 2" # use limited workers to avoid running out of memory
    branch_pattern: coverity_scan

before_script:
  - ${CXX} --version
  - ${CC} --version
  - cmake --version

script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then 
    make -j 2;
    fi

after_script:
  - cat /home/travis/build/AscEmu/AscEmu/ascemu_build/cov-int/build-log.txt
  - echo "===================================================================================================="
  - cat /home/travis/build/AscEmu/AscEmu/ascemu_build/cov-int/scm_log.txt

