os: linux
dist: bionic
language: cpp

compiler:
  - gcc
  - clang
  
git:
  depth: 1

env:
  global:
    - secure: "Zk3bAxnp4OHPMMZYOSoM2chuMZXomp7BFcT54/Ag6C8RCqtpqQ+E6yHRp861xdWSVo9uZ/uGmD1pwPiIUK8Vs80+OwhFVvtor2MGXyQKX1oFYBg0mo5Z3Xzy+OPa3e0YBbe6SSqdUzDE1hIa7OrU8GWciIMobWQS7XIBbWg3TFU="
  # Temp solution https://github.com/travis-ci/travis-ci/issues/4681
  jobs:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true    

before_install:
  - if [ "$COMPILER" = "g++-9" ]; then export CXX="g++-9" CC="gcc-9"; fi
  - if [ "$COMPILER" = "clang++-9" ]; then export CXX="clang++-9" CC="clang-9"; fi
    
jobs:
  #allow_failures:
  #  - compiler: clang
  include:
    # classic
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - zlib1g-dev
            - libssl-dev
            - libpcre3-dev
            - libbz2-dev
            - libmysqlclient-dev
            - libmysql++-dev
            - gcc-9
            - g++-9
      env: ASC_VERSION=Classic COMPILER=g++-9
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - zlib1g-dev
            - libssl-dev
            - libpcre3-dev
            - libbz2-dev
            - libmysqlclient-dev
            - libmysql++-dev
            - clang-9
            - g++-9
      env: ASC_VERSION=Classic COMPILER=clang++-9
    # tbc
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - zlib1g-dev
            - libssl-dev
            - libpcre3-dev
            - libbz2-dev
            - libmysqlclient-dev
            - libmysql++-dev
            - gcc-9
            - g++-9
      env: ASC_VERSION=TBC COMPILER=g++-9
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - zlib1g-dev
            - libssl-dev
            - libpcre3-dev
            - libbz2-dev
            - libmysqlclient-dev
            - libmysql++-dev
            - clang-9
            - g++-9
      env: ASC_VERSION=TBC COMPILER=clang++-9
    # wotlk
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - zlib1g-dev
            - libssl-dev
            - libpcre3-dev
            - libbz2-dev
            - libmysqlclient-dev
            - libmysql++-dev
            - gcc-9
            - g++-9
      env: ASC_VERSION=WotLK COMPILER=g++-9
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - zlib1g-dev
            - libssl-dev
            - libpcre3-dev
            - libbz2-dev
            - libmysqlclient-dev
            - libmysql++-dev
            - clang-9
            - g++-9
      env: ASC_VERSION=WotLK COMPILER=clang++-9
    # Cata
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - zlib1g-dev
            - libssl-dev
            - libpcre3-dev
            - libbz2-dev
            - libmysqlclient-dev
            - libmysql++-dev
            - gcc-9
            - g++-9
      env: ASC_VERSION=Cata COMPILER=g++-9
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - zlib1g-dev
            - libssl-dev
            - libpcre3-dev
            - libbz2-dev
            - libmysqlclient-dev
            - libmysql++-dev
            - clang-9
            - g++-9
      env: ASC_VERSION=Cata COMPILER=clang++-9
    # MoP
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - zlib1g-dev
            - libssl-dev
            - libpcre3-dev
            - libbz2-dev
            - libmysqlclient-dev
            - libmysql++-dev
            - gcc-9
            - g++-9
      env: ASC_VERSION=Mop COMPILER=g++-9
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - zlib1g-dev
            - libssl-dev
            - libpcre3-dev
            - libbz2-dev
            - libmysqlclient-dev
            - libmysql++-dev
            - clang-9
            - g++-9
      env: ASC_VERSION=Mop COMPILER=clang++-9
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true

install:
  - mkdir ascemu_build
  - cd ascemu_build
  - cmake ../ -DCMAKE_BUILD_TYPE=Release -DBUILD_WITH_WARNINGS=0 -DBUILD_TOOLS=1 -DUSE_PCH=1 -DASCEMU_VERSION=${ASC_VERSION}

before_script:
  - ${CXX} --version
  - ${CC} --version
  - cmake --version

script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then 
    make CXX=$COMPILER -j 4;
    fi

#after_script:
#  - cat /home/travis/build/AscEmu/AscEmu/ascemu_build/cov-int/build-log.txt
#  - echo "===================================================================================================="
#  - cat /home/travis/build/AscEmu/AscEmu/ascemu_build/cov-int/scm_log.txt
