sudo: false
dist: trusty
language: c++

compiler:
  - gcc
  - clang
  
git:
  depth: 1
  submodules: false

env:
  global:
    - secure: "Zk3bAxnp4OHPMMZYOSoM2chuMZXomp7BFcT54/Ag6C8RCqtpqQ+E6yHRp861xdWSVo9uZ/uGmD1pwPiIUK8Vs80+OwhFVvtor2MGXyQKX1oFYBg0mo5Z3Xzy+OPa3e0YBbe6SSqdUzDE1hIa7OrU8GWciIMobWQS7XIBbWg3TFU="
  # Temp solution https://github.com/travis-ci/travis-ci/issues/4681
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true    

before_install:
  - if [ "$COMPILER" = "g++-8" ]; then export CXX="g++-8" CC="gcc-8"; fi
  - if [ "$COMPILER" = "clang++-7" ]; then export CXX="clang++-7" CC="clang-7"; fi
    
matrix:
  #allow_failures:
  #  - compiler: clang
  include:
  # wotlk
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - zlib1g-dev
            - libssl-dev
            - libpcre3-dev
            - libbz2-dev
            - libmysqlclient-dev
            - libmysql++-dev
            - gcc-8
            - g++-8
      env: ASC_VERSION=WotLK COMPILER=g++-8
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - zlib1g-dev
            - libssl-dev
            - libpcre3-dev
            - libbz2-dev
            - libmysqlclient-dev
            - libmysql++-dev
            - clang-7
            - g++-7
      env: ASC_VERSION=WotLK COMPILER=clang++-7 
  # Cata
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - zlib1g-dev
            - libssl-dev
            - libpcre3-dev
            - libbz2-dev
            - libmysqlclient-dev
            - libmysql++-dev
            - gcc-8
            - g++-8
      env: ASC_VERSION=Cata COMPILER=g++-8
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - zlib1g-dev
            - libssl-dev
            - libpcre3-dev
            - libbz2-dev
            - libmysqlclient-dev
            - libmysql++-dev
            - clang-7
            - g++-7
      env: ASC_VERSION=Cata COMPILER=clang++-7
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true

install:
  - mkdir ascemu_build
  - cd ascemu_build
  - cmake ../ -DCMAKE_BUILD_TYPE=Release -DBUILD_WITH_WARNINGS=0 -DBUILD_TOOLS=0 -DASCEMU_VERSION=${ASC_VERSION} -DWITH_EXPERIMENTAL_FILESYSTEM=1
    
before_script:
  - ${CXX} --version
  - ${CC} --version
  - cmake --version

script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then 
    make CXX=$COMPILER -j 4;
    fi

#after_script:
#  - cat /home/travis/build/AscEmu/AscEmu/ascemu_build/cov-int/build-log.txt
#  - echo "===================================================================================================="
#  - cat /home/travis/build/AscEmu/AscEmu/ascemu_build/cov-int/scm_log.txt
