image: Visual Studio 2017

branches:
  except:
    - coverity_scan

environment:
  matrix:
  - ASC_VERSION: WotLK
    VS_VER: Visual Studio 15 2017
  - ASC_VERSION: WotLK
    VS_VER: Visual Studio 15 2017 Win64
  - ASC_VERSION: Cata
    VS_VER: Visual Studio 15 2017
  - ASC_VERSION: Cata
    VS_VER: Visual Studio 15 2017 Win64

configuration: Release

init:
  - cmd: cmake --version
  - cmd: msbuild /version

install:
  - git submodule update --init --recursive
  
before_build:
  - cmd: echo %VS_VER%
  - cmd: echo %Configuration%

build_script:
  - cmd: mkdir ascemu_build
  - cmd: cd ascemu_build
  - cmd: cmake ../ -G "%VS_VER%" -DBUILD_WITH_WARNINGS=0 -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DBUILD_TOOLS=1 -DASCEMU_VERSION=%ASC_VERSION%
  - cmd: msbuild Ascemu.sln
