version: 2.1

jobs:
  "Classic":
    docker:
      - image: "cimg/base:2022.04-20.04"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'sudo apt-get update && sudo apt-get install -y && sudo rm -rf /var/lib/apt/lists/*'
#      - run:
#          name: Installing GCC
#          command: 'sudo apt-get update && sudo apt-get install -y gcc-9 g++'
      - run:
          name: Install CMAKE
          command: 'sudo apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install deps
          command: |
            sudo apt-get update && sudo apt-get install -y zlib1g-dev
            sudo apt-get update && sudo apt-get install -y libssl-dev
            sudo apt-get update && sudo apt-get install -y libpcre3-dev
            sudo apt-get update && sudo apt-get install -y libbz2-dev
            sudo apt-get update && sudo apt-get install -y libmysqlclient-dev
            sudo apt-get update && sudo apt-get install -y libmysql++-dev
      - run:
          name: Check versions
          command: |
            gcc --version
            cmake --version
      - run:
          name: Build Classic
          command: |
            mkdir ascemu_classic
            cd ascemu_classic
            cmake ../ -DCMAKE_BUILD_TYPE=Release -DBUILD_WITH_WARNINGS=0 -DBUILD_TOOLS=0 -DUSE_PCH=1 -DASCEMU_VERSION=Classic
            cd ..
            cd ascemu_classic
            make -j 4
            cd ..
  "TBC":
    docker:
      - image: "cimg/base:2022.04-20.04"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'sudo apt-get update && sudo apt-get install -y && sudo rm -rf /var/lib/apt/lists/*'
#      - run:
#          name: Installing GCC
#          command: 'sudo apt-get update && sudo apt-get install -y gcc-9 g++'
      - run:
          name: Install CMAKE
          command: 'sudo apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install deps
          command: |
            sudo apt-get update && sudo apt-get install -y zlib1g-dev
            sudo apt-get update && sudo apt-get install -y libssl-dev
            sudo apt-get update && sudo apt-get install -y libpcre3-dev
            sudo apt-get update && sudo apt-get install -y libbz2-dev
            sudo apt-get update && sudo apt-get install -y libmysqlclient-dev
            sudo apt-get update && sudo apt-get install -y libmysql++-dev
      - run:
          name: Check versions
          command: |
            gcc --version
            cmake --version
      - run:
          name: Build TBC
          command: |
            mkdir ascemu_bc
            cd ascemu_bc
            cmake ../ -DCMAKE_BUILD_TYPE=Release -DBUILD_WITH_WARNINGS=0 -DBUILD_TOOLS=0 -DUSE_PCH=1 -DASCEMU_VERSION=TBC
            cd ..
            cd ascemu_bc
            make -j 4
            cd ..
            
  "WotLK":
    docker:
      - image: "cimg/base:2022.04-20.04"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'sudo apt-get update && sudo apt-get install -y && sudo rm -rf /var/lib/apt/lists/*'
#      - run:
#          name: Installing GCC
#          command: 'sudo apt-get update && sudo apt-get install -y gcc-9 g++'
      - run:
          name: Install CMAKE
          command: 'sudo apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install deps
          command: |
            sudo apt-get update && sudo apt-get install -y zlib1g-dev
            sudo apt-get update && sudo apt-get install -y libssl-dev
            sudo apt-get update && sudo apt-get install -y libpcre3-dev
            sudo apt-get update && sudo apt-get install -y libbz2-dev
            sudo apt-get update && sudo apt-get install -y libmysqlclient-dev
            sudo apt-get update && sudo apt-get install -y libmysql++-dev
      - run:
          name: Check versions
          command: |
            gcc --version
            cmake --version
      - run:
          name: Build WotLK
          command: |
            mkdir ascemu_wotlk
            cd ascemu_wotlk
            cmake ../ -DCMAKE_BUILD_TYPE=Release -DBUILD_WITH_WARNINGS=0 -DBUILD_TOOLS=0 -DUSE_PCH=1 -DASCEMU_VERSION=WotLK
            cd ..
            cd ascemu_wotlk
            make -j 4
            cd ..
            
  "Cata":
    docker:
      - image: "cimg/base:2022.04-20.04"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'sudo apt-get update && sudo apt-get install -y && sudo rm -rf /var/lib/apt/lists/*'
#      - run:
#          name: Installing GCC
#          command: 'sudo apt-get update && sudo apt-get install -y gcc-9 g++'
      - run:
          name: Install CMAKE
          command: 'sudo apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install deps
          command: |
            sudo apt-get update && sudo apt-get install -y zlib1g-dev
            sudo apt-get update && sudo apt-get install -y libssl-dev
            sudo apt-get update && sudo apt-get install -y libpcre3-dev
            sudo apt-get update && sudo apt-get install -y libbz2-dev
            sudo apt-get update && sudo apt-get install -y libmysqlclient-dev
            sudo apt-get update && sudo apt-get install -y libmysql++-dev
      - run:
          name: Check versions
          command: |
            gcc --version
            cmake --version
      - run:
          name: Build Cata
          command: |
            mkdir ascemu_cata
            cd ascemu_cata
            cmake ../ -DCMAKE_BUILD_TYPE=Release -DBUILD_WITH_WARNINGS=0 -DBUILD_TOOLS=0 -DUSE_PCH=1 -DASCEMU_VERSION=Cata
            cd ..
            cd ascemu_cata
            make -j 4
            cd ..
            
  "Mop":
    docker:
      - image: "cimg/base:2022.04-20.04"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'sudo apt-get update && sudo apt-get install -y && sudo rm -rf /var/lib/apt/lists/*'
#      - run:
#          name: Installing GCC
#          command: 'sudo apt-get update && sudo apt-get install -y gcc-9 g++'
      - run:
          name: Install CMAKE
          command: 'sudo apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install deps
          command: |
            sudo apt-get update && sudo apt-get install -y zlib1g-dev
            sudo apt-get update && sudo apt-get install -y libssl-dev
            sudo apt-get update && sudo apt-get install -y libpcre3-dev
            sudo apt-get update && sudo apt-get install -y libbz2-dev
            sudo apt-get update && sudo apt-get install -y libmysqlclient-dev
            sudo apt-get update && sudo apt-get install -y libmysql++-dev
      - run:
          name: Check versions
          command: |
            gcc --version
            cmake --version
      - run:
          name: Build Mop
          command: |
            mkdir ascemu_mop
            cd ascemu_mop
            cmake ../ -DCMAKE_BUILD_TYPE=Release -DBUILD_WITH_WARNINGS=0 -DBUILD_TOOLS=0 -DUSE_PCH=1 -DASCEMU_VERSION=Mop
            cd ..
            cd ascemu_mop
            make -j 4
            cd ..
            
workflows:
  version: 2.1
  build:
    jobs:
      - "Classic"
      - "TBC"
      - "WotLK"
      - "Cata"
      - "Mop"
